[project]
name = "trust-score"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "accelerate>=1.12.0",
    "adapters>=1.2.0",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.8",
    "pandas>=3.0.0",
    "pyalex>=0.19",
    "pyarrow>=23.0.0",
    "scikit-learn>=1.8.0",
    "tenacity>=9.1.2",
    "torch>=2.10.0",
]
